// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { appControllerGetHello, type Options, telegramControllerGetMessagesInRange } from '../sdk.gen';
import type { AppControllerGetHelloData, TelegramControllerGetMessagesInRangeData, TelegramControllerGetMessagesInRangeResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const appControllerGetHelloQueryKey = (options?: Options<AppControllerGetHelloData>) => createQueryKey('appControllerGetHello', options);

export const appControllerGetHelloOptions = (options?: Options<AppControllerGetHelloData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof appControllerGetHelloQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await appControllerGetHello({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: appControllerGetHelloQueryKey(options)
});

export const telegramControllerGetMessagesInRangeQueryKey = (options: Options<TelegramControllerGetMessagesInRangeData>) => createQueryKey('telegramControllerGetMessagesInRange', options);

/**
 * Получить сообщения канала за период
 */
export const telegramControllerGetMessagesInRangeOptions = (options: Options<TelegramControllerGetMessagesInRangeData>) => queryOptions<TelegramControllerGetMessagesInRangeResponse, DefaultError, TelegramControllerGetMessagesInRangeResponse, ReturnType<typeof telegramControllerGetMessagesInRangeQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await telegramControllerGetMessagesInRange({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: telegramControllerGetMessagesInRangeQueryKey(options)
});
