// This file is auto-generated by @hey-api/openapi-ts

export { appControllerGetHelloOptions, appControllerGetHelloQueryKey, type QueryKey, telegramControllerGetMessagesInRangeOptions, telegramControllerGetMessagesInRangeQueryKey } from './@tanstack/react-query.gen';
export { client, type CreateClientConfig } from './client.gen';
export { appControllerGetHello, type Options, telegramControllerGetMessagesInRange } from './sdk.gen';
export type { AppControllerGetHelloData, AppControllerGetHelloResponses, ClientOptions, MessageResponseDto, TelegramControllerGetMessagesInRangeData, TelegramControllerGetMessagesInRangeResponse, TelegramControllerGetMessagesInRangeResponses } from './types.gen';
export { zMessageResponseDto, zTelegramControllerGetMessagesInRangeQuery, zTelegramControllerGetMessagesInRangeResponse } from './zod.gen';
