// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AppControllerGetHelloData, AppControllerGetHelloResponses, TelegramControllerGetMessagesInRangeData, TelegramControllerGetMessagesInRangeResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const appControllerGetHello = <ThrowOnError extends boolean = false>(options?: Options<AppControllerGetHelloData, ThrowOnError>) => (options?.client ?? client).get<AppControllerGetHelloResponses, unknown, ThrowOnError>({ url: '/', ...options });

/**
 * Получить сообщения канала за период
 */
export const telegramControllerGetMessagesInRange = <ThrowOnError extends boolean = false>(options: Options<TelegramControllerGetMessagesInRangeData, ThrowOnError>) => (options.client ?? client).get<TelegramControllerGetMessagesInRangeResponses, unknown, ThrowOnError>({ url: '/telegram/messages', ...options });
