// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type MessageResponseDto = {
    /**
     * Уникальный идентификатор сообщения
     */
    id: number;
    /**
     * Дата публикации сообщения
     */
    date: string;
    /**
     * Текст сообщения
     */
    message: string;
    /**
     * Флаг наличия медиа-вложений
     */
    hasMedia: boolean;
};

export type AppControllerGetHelloData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type AppControllerGetHelloResponses = {
    200: unknown;
};

export type TelegramControllerGetMessagesInRangeData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Username канала (например, "kaliningradtop")
         */
        channel: string;
        /**
         * Слово для поиска
         */
        searchWord: string;
        /**
         * Начало периода
         */
        startDate: string;
        /**
         * Конец периода
         */
        endDate: string;
    };
    url: '/telegram/messages';
};

export type TelegramControllerGetMessagesInRangeResponses = {
    /**
     * Список сообщений
     */
    200: Array<MessageResponseDto>;
};

export type TelegramControllerGetMessagesInRangeResponse = TelegramControllerGetMessagesInRangeResponses[keyof TelegramControllerGetMessagesInRangeResponses];
